{% set name = "kfp-pipeline-spec" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py3/{{ name[0] }}/{{ name }}/kfp_pipeline_spec-{{ version }}-py3-none-any.whl
    sha256: 5384e710aef8268eb20ee147b2a0a6cfc3b0cbeef037cad89f46ab877375e1aa
build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed ./kfp_pipeline_spec-{{ version }}-py3-none-any.whl

requirements:
  host:
    - python >=3.7.0
    - pip
  run:
    - python >=3.7.0
    - protobuf >=4.21.1,<5
    - googleapis-common-protos

test:
  imports:
    - kfp.pipeline_spec.pipeline_spec_pb2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kubeflow/pipelines
  summary: Kubeflow Pipelines pipeline spec
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chensun
    - manuelwalserqc
